apiVersion: v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
    openshift.io/generated-by: GetupCloudWebConsole
  creationTimestamp: null
  labels:
    app: site
    getup.io/component-name: site
  name: wild-siteab-workshop01-getup-io
spec:
  host: siteab-workshop01.getup.io
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: site
    weight: 70
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2016-12-07T13:10:39Z
      status: "True"
      type: Admitted
    host: siteab-workshop01.getup.io
    routerName: router
